### PR TITLE
Plotlaplace

### PR DESCRIPTION
**Pull request by robhau**
In this pull request there are three new functions for sig_sys_tools.py:

> `plot_splane` : function to plot the s plane, when zeros, poles and gain factor of H(s) are given
> `group_delay`: function to calculate the group delay , when zeros, poles and gain factor of H(s) are given
> `plot_clti_analysis` plots impulse response, step response, frequency response (level, phase, group delay), s-plane, when zeros, poles and gain factor of H(s) are given

The color of the ROC in the s-plane could maybe be changed, i dont know the ideal color for the best visibility.

### CODE REVIEW

**Comment by fs446** [comment]
Please provide minimum examples that call these new functions such that we can check it conveniently in i) a Jupyter notebook and ii) a pure Python script. For example 'plot_splane' is not working for me using the conda environment that is suggested in readme.md, so we need to figure in detail what's going on.

We could check these functions with the system from https://github.com/spatialaudio/signals-and-systems-exercises/blob/master/laplace_system_analysis/lowpass2nd_44EB4169E9.ipynb

**Comment by robhau** [comment]
I uploaded a jupyter notebook (https://github.com/spatialaudio/signals-and-systems-exercises/blob/4465cfabbe5ab2d36c58192c41d472d995d2e6b4/laplace_system_analysis/TestingNewFunctions.ipynb) that contains the three functions with given inputs, it just has to be run. My environment is Miniconda3, but that is only a small version of Anaconda (https://docs.conda.io/en/latest/miniconda.html).

**Comment by fs446** [comment]
ROC area seems to be wrong for some values, please check and fix
- `plot_clti_analysis(z=np.array([-1, -1]),p=np.array([-3/4+1j,-3/4-1j]),k=25/16)`
- `plot_splane(z=[-2],p=[-1],k=3)`

in case z and p have same value, e.g.
`plot_splane(z=[-1],p=[-1],k=3)`
we get message: `UserWarning: Attempting to set identical left == right == -1.0 results in singular transformations; automatically expanding. plt.axis([xmin,xmax,ymin,ymax])`
this does however not happen for e.g. `plot_splane(z=[-1,-2],p=[-1,-2],k=1)`
Don't know if we should check for compensation pole/zero-values?

**Comment by robhau** [comment]
I found my fault:
in plot_splane we look for the max{Res(x) | x elem z,p} (and min(Imag) to get the bounds of the diagram. In the first case we have xmin ==xmax and ymin == ymax. Because of that, `plt.axis([xmin,xmax,ymin,ymax]` gives this message.
Now there are two ways:
First : looking if `|xmax-xmin| == 0 ` (same for y-values) and do:
`xmax = xmax+const
xmin = xmin + const`
Second : if we want, that the diagram is at least "2const" wide in one direction, then we look if
`|xmax-xmin| < const`(same for y-values) and do:
`xmax = xmin + np.abs(xmax-xmin)/2+eps
 xmin = xmax - 2*eps`
I implemented the second version, for the first version we just have to change the boolean expression in line 232 and 239. The second version becomes uglier from very small values (eg. for `z=np.array([-0.001])` and `p=np.array([-0.0001])`), because it seems that they are on the same position.

Edit:
When i execute `group_splane` in "TestingNewFunctions.ipynb" or in "lowpass2nd_44EB4169E9.ipynb" i have to execute `%matplotlib inline` or `%matplotlib` to get shown a plot. Is that normal?

**Pull request merged**
